/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cursojavasena;

import java.awt.Color;

/**
 *
 * @author Nicolas Espitia
 */
public class Acti1 extends java.applet.Applet {

    /** Initializes the applet Acti1 */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        palabras = new javax.swing.JLabel();
        bot1 = new javax.swing.JButton();
        bot2 = new javax.swing.JButton();
        bot3 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        palabras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras.setText("SERVICIO NACIONAL DE APRENDIZAJE (SENA)");
        palabras.setToolTipText("");
        palabras.setAlignmentY(5.0F);
        add(palabras, java.awt.BorderLayout.PAGE_START);
        palabras.getAccessibleContext().setAccessibleName("palabra");

        bot1.setText("bot1");
        bot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot1ActionPerformed(evt);
            }
        });
        bot1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bot1KeyPressed(evt);
            }
        });
        add(bot1, java.awt.BorderLayout.CENTER);

        bot2.setText("bot2");
        bot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot2ActionPerformed(evt);
            }
        });
        add(bot2, java.awt.BorderLayout.SOUTH);

        bot3.setText("bot3");
        bot3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot3ActionPerformed(evt);
            }
        });
        add(bot3, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void bot1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bot1KeyPressed
        
    }//GEN-LAST:event_bot1KeyPressed

    private void bot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot1ActionPerformed
        palabras.setForeground(Color.yellow);
    }//GEN-LAST:event_bot1ActionPerformed

    private void bot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot2ActionPerformed
        palabras.setForeground(Color.red);
    }//GEN-LAST:event_bot2ActionPerformed

    private void bot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot3ActionPerformed
        palabras.setForeground(Color.pink);
    }//GEN-LAST:event_bot3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot1;
    private javax.swing.JButton bot2;
    private javax.swing.JButton bot3;
    private javax.swing.JLabel palabras;
    // End of variables declaration//GEN-END:variables

}
