/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cursojavasena;

/**
 *
 * @author Nicolas Espitia
 */
public class Acti1_1 extends java.applet.Applet {

    /**
     * Initializes the applet Acti1_1
     */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textu = new javax.swing.JLabel();
        boton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        textu.setText(".");
        add(textu, java.awt.BorderLayout.CENTER);

        boton1.setText("Poner texto");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        add(boton1, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        textu.setText("El botón ha sido presionado.");
    }//GEN-LAST:event_boton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JLabel textu;
    // End of variables declaration//GEN-END:variables
}
